version: 1.0.{build}
environment:
  githubtoken:
    secure: W27HI1sXnMlvqMNTJYW01BzNiu/8QqWkkFSK5n4cst6F6FT7QjhkC7UcvHN50hoi
build_script:
- ps: "git config --global credential.helper store\ngit config --global user.name \"Monster Deploy\"\ngit config --global user.email contact@aspnetmonsters.com\ngit config --global push.default simple\nAdd-Content \"$env:USERPROFILE\\.git-credentials\" \"https://$($env:githubtoken):x-oauth-basic@github.com`n\"\ntype \"$env:USERPROFILE\\.git-credentials\"\ntype ~\\.git-credentials\n npm install\n npm install -g hexo\n hexo generate\n\n(Get-Content .\\_config.yml).replace(\"git@github.com:AspNetMonsters/website.git\", \"https://monsters-deploy@github.com/AspNetMonsters/website.git\") | Set-Content .\\_config.yml\n\n xcopy .\public\* .\.deploy_git\ /s /y \n cd .deploy_git\ngit init .\n git add -A \n git commit -m 'deploy'\ngit push -u https://github.com/AspNetMonsters/website.git HEAD:blog_output"
test: off
