# Header
menu:
  Home: /
  About: /2016/01/welcome
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: false

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# Miscellaneous
google_analytics: UA-58850513-2
favicon: /images/favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id: