# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

permissions:
      id-token: write

on:
  push:
    branches: [ master ]
  workflow_dispatch: 
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get NodeJS Version from package.json
      run: |
        echo "$(cat ./package.json)" | jq .engines.node | xargs -I {} echo "NodeVersion="{} >> $GITHUB_ENV
    - name: Use Node.js ${{ env.NodeVersion }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NodeVersion }}
    - run: npm ci
    - run: npx hexo generate
    - name: Azure Login
      uses: Azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: Azure CLI Action
      uses: Azure/cli@v1
      with:
        inlineScript: |
            az account show
            az storage blob upload-batch --account-name aspnetmonsters -s ./public -d '$web' --overwrite
            az cdn endpoint purge -n aspnetmonsters -g aspnetmonsters --profile-name  aspnetmonsters --no-wait --content-paths '/' '/index.html'
        
        
        
